name: Continuous Integration

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-elixir@v1.2.0
        with:
          otp-version: 22.1.x
          elixir-version: 1.10.0

      - uses: actions/cache@v1
        with:
          path: _build
          key: ${{ runner.os }}-build-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: |
            ${{ runner.os }}-build-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
            ${{ runner.os }}-build-

      - uses: actions/cache@v1
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: |
            ${{ runner.os }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
            ${{ runner.os }}-mix-

      - name: Fetch Dependencies
        run: mix deps.get

      - name: Compile
        run: mix compile --warnings-as-errors

  code_analysis:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-elixir@v1.2.0
        with:
          otp-version: 22.1.x
          elixir-version: 1.10.0

      - uses: actions/cache@v1
        with:
          path: _build
          key: ${{ runner.os }}-build-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: |
            ${{ runner.os }}-build-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
            ${{ runner.os }}-build-

      - uses: actions/cache@v1
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: |
            ${{ runner.os }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
            ${{ runner.os }}-mix-

      - uses: actions/cache@v1
        with:
          path: priv/plts
          key: ${{ runner.os }}-plt-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: |
            ${{ runner.os }}-plt-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
            ${{ runner.os }}-plt-

      - name: Fetch Dependencies
        run: mix deps.get

      - name: Formatter Analysis
        run: mix format --check-formatted

      - name: Credo Analysis
        run: mix credo --strict

      - name: Sobelow Analysis
        run: mix sobelow --config

      - name: Dialyzer Analysis
        run: mix dialyzer --plt

  test:
    runs-on: ubuntu-latest
    needs: build

    services:
      db:
        image: postgres:11
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
          API_DOCS: 1
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-elixir@v1.2.0
        with:
          otp-version: 22.1.x
          elixir-version: 1.10.0

      - uses: actions/cache@v1
        with:
          path: _build
          key: ${{ runner.os }}-test-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: |
            ${{ runner.os }}-test-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
            ${{ runner.os }}-test-

      - uses: actions/cache@v1
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: |
            ${{ runner.os }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
            ${{ runner.os }}-mix-

      - name: Fetch Dependencies
        run: mix deps.get

      - name: Run Tests
        run: mix coveralls
